In [1]:
''' Example1'''

' Example1'

In [2]:
import numpy as np
empty_array = np.empty(2, dtype=int)

In [8]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [9]:
arange_array = np.arange(0, 10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
randint_array = np.random.randint(1, 10,(3, 3))
print(randint_array)

[[9 6 6]
 [7 7 4]
 [5 8 3]]


In [12]:
rand_array = np.random.rand(2, 3)
print(rand_array)

[[0.70880135 0.03290659 0.20739193]
 [0.9717547  0.53950017 0.61156876]]


In [13]:
'''Example2: '''

'Example2: '

In [15]:
import numpy as np
arr = np.array([1 , 2, 3, 4, 5])
print("arr :", arr)
print("Shape of arr:", arr.shape)
print("Size of arr:", arr.size)
print("Data type of arr :", arr.dtype)
print("Number of dimensions of arr:", arr.ndim) 

arr : [1 2 3 4 5]
Shape of arr: (5,)
Size of arr: 5
Data type of arr : int32
Number of dimensions of arr: 1


In [16]:
'''Example 3'''

'Example 3'

In [17]:
import numpy as np
arr1d = np.array([1 , 2, 3, 4, 5])
first_element = arr1d[0]
print("The first element of arr1d: ", first_element )
last_element = arr1d[-1]
print("The last element of arr1d: ",last_element )


The first element of arr1d:  1
The last element of arr1d:  5


In [18]:
'''Example 4'''

'Example 4'

In [19]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
element_1_2 = arr2d[0, 1] 
print(element_1_2 ) 


[[1 2 3]
 [4 5 6]]
2
